name = "packageDevTest1"
uuid = "269f01f6-2a8d-48ce-a253-28e9484883a6"
authors = ["bryanfelixg <felix077@umn.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
